[config]
algorithms = ["NN", "RNN", "SA"]
# instance_sizes = [15]
mode = "correctness"
greedy = true
swap_algo = 2       # 0 - swap, 1 - insert, 2 - invert
T0 = 1000           # temperatura poczatkowa
alpha = 0.99        # wspolczynnik schlodzenia
epoch_length = 1000 # dlugosc epoki
cooling_scheme = 0  # schemat schladzania

[data]
input = "/home/grzeg/PEA/data/xqf131.tsp"
optimal = "/home/grzeg/PEA/optimal/xqf131.tour"
output_path = "../result/result_corr_5-14.csv"