[config]
algorithms = ["NN", "RNN", "TS"]
# instance_sizes = [15]
mode = "correctness"
iterations = 1000
tabu_size = 20
cadence = 10
no_aspiration = false
greedy = true
swap_algo = 0

[data]
input = "/home/grzeg/PEA/data/xqf131.tsp"
optimal = "/home/grzeg/PEA/optimal/xqf131.tour"
output_path = "../result/result_corr_5-14.csv"