[config]
algorithms = ["RNN", "TS"]
# instance_sizes = [15]
mode = "correctness"
iterations = 1000
tabu_size = 20
cadence = 10
no_aspiration = false
greedy = true
swap_algo = 0

[data]
input = "/home/grzegorz/Desktop/PEA/Projekt1/data_zajecia/ft70.txt"
optimal_value = 38673
output_path = "../result/result_corr_5-14.csv"