[config]
algorithms = ["RNN", "TS"]
mode = "correctness"
iterations = 1000
tabu_size = 20
cadence = 10
no_aspiration = false
greedy = true
swap_algo = 0

[data]
input = "/home/grzeg/PEA/atsp/rbg323.atsp"
optimal_value = 1326
output_path = "result/result_rbg323_no_asp.csv"