[config]
algorithms = ["BnB"]
instance_sizes = [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
mode = "performance"
repetitions = 20
search_algorithm = "Best_First"
is_symmetric = true

[data]
input = "/home/grzeg/PEA/data_zajecia/br17.txt"
optimal = "/home/grzeg/PEA/data_zajecia/br17.txt"
output_path = "/home/grzeg/PEA/result/ub/result_BF_perf.csv"