[config]
algorithms = ["BnB"]
instance_sizes = [10]
mode = "correctness"
search_algorithm = "DFS1"

[data]
input = "/home/grzeg/PEA/data_zajecia/tsp_10a.txt"
optimal = "/home/grzeg/PEA/data_zajecia/br17.txt"
output_path = "/home/grzeg/PEA/result/result_DFS.csv"