[config]
algorithms = ["RNN", "NN", "RAND"]
mode = "correctness"
iterations = 10000

[data]
input = "/home/grzegorz/Desktop/PEA/Projekt1/data/ley2323.tsp"
optimal = "/home/grzegorz/Desktop/PEA/Projekt1/optimal/ley2323.tour"
output_path = "/home/grzegorz/Desktop/PEA/Projekt1/result/result_ley2323.csv"